sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t rent-real-estate-api ./rentRealEstate
  - docker build -t real_estate ./rentRealEstate

before_script:
  - docker-compose up