version: "3"
services:
  rent-real-estate-postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rent_real_estate
    ports:
      - "5432:5432"
  rent-real-estate-service:
    image: rent-real-estate-api
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://rent-real-estate-postgres:5432/rent_real_estate
    ports:
      - "8080:8080"
    depends_on:
      - rent-real-estate-postgres