version: "3"
services:
  real-estate-postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=real_estate
    ports:
      - "5432:5432"
  real-estate-service:
    image: ak2748/real_estate
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://real-estate-postgres:5432/real_estate
      - KUMULUZEE_SERVER_BASEURL=http://real-estate-service:8080
    ports:
      - "8080:8080"
    depends_on:
      - real-estate-postgres

  rent-real-estate-postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rent_real_estate
    ports:
      - "5433:5432"
  rent-real-estate-service:
    image: ak2748/rent-real-estate-api
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://rent-real-estate-postgres:5432/rent_real_estate
      - KUMULUZEE_SERVER_BASEURL=http://rent-real-estate-service:8081
    ports:
      - "8081:8081"
    depends_on:
      - rent-real-estate-postgres

  rent-real-estate-history-service:
    image: ak2748/real-estate-history
    environment:
      - KUMULUZEE_SERVER_BASEURL=http://rent-real-estate-history-service:8082
    ports:
      - "8082:8082"
    depends_on:
      - real-estate-service
      - rent-real-estate-service

  real-estate-users-service:
    image: ak2748/real-estate-users
    environment:
      - KUMULUZEE_SERVER_BASEURL=http://real-estate-users-service:8083
    ports:
      - "8083:8083"

  real-estate-comment-service:
    image: ak2748/real-estate-comment
    environment:
      - KUMULUZEE_SERVER_BASEURL=http://real-estate-comment-service:8084
    ports:
      - "8084:8084"