version: "3"
services:
  real-estate-postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=real_estate
  real-estate-service:
    image: real_estate
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://real-estate-postgres:5432/real_estate
    ports:
      - "8080:8080"
    depends_on:
      - real-estate-postgres

  rent-real-estate-postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rent_real_estate
  rent-real-estate-service:
    image: rent-real-estate-api
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://rent-real-estate-postgres:5432/rent_real_estate
    ports:
      - "8081:8080"
    depends_on:
      - rent-real-estate-postgres