kumuluzee:
  name: realEstateDistance
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8086
    http:
      port: 8086
  discovery:
    etcd:
      hosts: http://192.168.42.7:2379
    ttl: 30
    ping-interval: 5
  health:
    servlet:
      enabled: true
      mapping: /health
    checks:
      http-health-check:
        - connection-url: http://localhost:8086/realEstateDistance
  metrics:
    servlet:
      enabled: true
      mapping: /metrics
    web-instrumentation:
      - name: real-estate-distance-endpoint
        url-pattern: /realEstateDistance
  logs:
    config-file-location: realEstateDistance/src/main/resources/log4j2.xml