kumuluzee:
  name: rentRealEstateService
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/RentRealEstateDS
      connection-url: jdbc:postgresql://localhost:5433/rent_real_estate
      username: postgres
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://192.168.1.18:2379
    ttl: 30
    ping-interval: 5
  health:
    servlet:
      enabled: true
      mapping: /health
    checks:
      data-source-health-check:
        jndi-name: jdbc/RentRealEstateDS
      http-health-check:
        - connection-url: http://localhost:8081/rentRealEstate
  metrics:
    servlet:
      enabled: true
      mapping: /metrics
    web-instrumentation:
      - name: rent-real-estate-endpoint
        url-pattern: /rentRealEstate
  logs:
    config-file-location: realEstate/src/main/resources/log4j2.xml