kumuluzee:
  name: realEstateUsers
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  discovery:
    etcd:
      hosts: http://192.168.42.7:2379
    ttl: 30
    ping-interval: 5
  health:
    servlet:
      enabled: true
      mapping: /health
    checks:
      http-health-check:
        - connection-url: http://localhost:8083/realEstateUsers
  metrics:
    servlet:
      enabled: true
      mapping: /metrics
    web-instrumentation:
      - name: real-estate-users-endpoint
        url-pattern: /realEstateUsers
  logs:
    config-file-location: realEstateUsers/src/main/resources/log4j2.xml