apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: real-estate-distance-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: realEstateDistance
    spec:
      containers:
      - image: ak2748/real-estate-distance
        name: real-estate-distance-service
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: airbnb
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://real-estate-distance-service:8086
        ports:
        - containerPort: 8086
          name: server
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8086
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: real-estate-distance
spec:
  type: LoadBalancer
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: realEstateDistance