apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: real-estate-users-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: realEstateUsers
    spec:
      containers:
      - image: ak2748/real-estate-users
        name: real-estate-users-service
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: airbnb
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://real-estate-users-service:8081
        ports:
        - containerPort: 8084
          name: server
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8084
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: real-estate-users
spec:
  type: LoadBalancer
  ports:
  - port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app: realEstateUsers