apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: real-estate-history-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: realEstateHistory
    spec:
      containers:
      - image: ak2748/real-estate-history
        name: real-estate-history-service
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: airbnb
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://real-estate-history-service:8082
        ports:
        - containerPort: 8082
          name: server
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: real-estate-history
spec:
  type: LoadBalancer
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: realEstateHistory