apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: real-estate-ads-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: realEstateAds
    spec:
      containers:
      - image: ak2748/real-estate-ads
        name: real-estate-ads-service
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: airbnb
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://real-estate-ads-service:8081
        ports:
        - containerPort: 8087
          name: server
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8087
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: real-estate-ads
spec:
  type: LoadBalancer
  ports:
  - port: 8087
    protocol: TCP
    targetPort: 8087
  selector:
    app: realEstateAds