kumuluzee:
  name: rentRealEstateService
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/RentRealEstateDS
      connection-url: jdbc:postgresql://localhost:5432/rent_real_estate
      username: postgres
      password: postgres
      max-pool-size: 20