kumuluzee:
  name: realEstateRecommendation
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8085
    http:
      port: 8085
  discovery:
    etcd:
      hosts: http://192.168.42.7:2379
    ttl: 30
    ping-interval: 5
  health:
    servlet:
      enabled: true
      mapping: /health
    checks:
      http-health-check:
        - connection-url: http://localhost:8085/realEstateRecommendation
  metrics:
    servlet:
      enabled: true
      mapping: /metrics
    web-instrumentation:
      - name: real-estate-recommendation-endpoint
        url-pattern: /realEstateRecommendation
  logs:
    config-file-location: realEstateRecommendation/src/main/resources/log4j2.xml