kumuluzee:
  name: realEstateHistoryService
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  discovery:
    etcd:
      hosts: http://192.168.42.7:2379
    ttl: 30
    ping-interval: 5
  health:
    servlet:
      enabled: true
      mapping: /health
  metrics:
    servlet:
      enabled: true
      mapping: /metrics
    web-instrumentation:
      - name: real-estate-history-endpoint
        url-pattern: /realEstateHistory
  logs:
    config-file-location: realEstate/src/main/resources/log4j2.xml