kumuluzee:
  name: realEstateHistoryService
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  discovery:
    etcd:
      hosts: http://192.168.42.7:2379
    ttl: 30
    ping-interval: 5